### ISSUE TITLE
1.0 Release

### ISSUE THREAD

**Issue by tmcdonell** [AccelerateHS/accelerate#285]
Taskboard for 1.0 release of Accelerate.

This will be a first stable release and include the fixes to memory management (addressed via Lifetimes), changes to `EltRepr` (required for for the LLVM backends), and basically everything that we have so far except streaming computations.

Tasks / milestones:
- [x] Windows support (with help from @mwu-tow)
    - `llvm-general` on windows?
- [ ] Website/wiki for tutorials, documentation

Bug list:
- [x] #339 GHC-7.10 RTS crash
  - This is a bug in GHC-7.10 which I have not yet been able to work around, which means we are blocked on a release of `llvm-general` compatible with GHC-8.
- [x] #286
- [x] #264 
- [x] #261 ("invalid device context"; some programs randomly succeed/fail at startup)
    - This is very difficult to test but seems fine now?
- [x] #218 
- [x] #188 
- [x] ~~#167~~ (this is kinda just nvidia's problem...)
- [x] #139 (I improved the haddocks a bit, more documentation / actual website to come)
- [x] #130
- [x] ~~#110~~ (bump to 1.1)
- [x] #52 (sort of... [https://github.com/tmcdonell/mwc-random-accelerate](mwc-random-accelerate))
- [x] #51 
- [x] #10

Bump (delaying accelerate-cuda-1.0)
- #234 windows support (statement expressions)
- #228 (cuda backend required commutative reduction operators)

Task list for package releases:
- [x] accelerate
- [x] accelerate-cuda
- [x] accelerate-llvm
- [x] accelerate-llvm-native
- [x] accelerate-llvm-ptx
- [x] accelerate-io
- [x] accelerate-fft
- [x] accelerate-examples
- [ ] accelerate-lulesh (standalone or integrated with accelerate-examples)
- [x] accelerate-bignum
- [x] cuda
- [ ] cufft (@robeverest is this up to date?)
  - [ ] patches for windows support
- [x] mwc-random-accelerate
- [x] colour-accelerate
- [x] gloss-accelerate
- [x] gloss-raster-accelerate
- [x] lens-accelerate
- [ ] linear-accelerate
  - [ ] need to send patches to upstream, or start managing ourselves (it is a complete rewrite)

**Comment by cpdurham** [comment]
Hey Trevor, thanks for the updated versions!

Did that memory code help you at all? Especially that "Internal representation of Storable array has changed" error?

Also, any chance that issue #228 can go into the milestone?

    print $ C.run1 (A.fold1 (\_ b -> b)) $ A.fromList (Z :. 3) ([1,0,1] :: [Int]) 

is still returning 0 when the interpreter returns 1

**Comment by tmcdonell** [comment]
If I remember correctly the improvements to the memory manager are mostly to address out-of-memory situations, where we want to shuffle some data we aren't using at the moment back to the CPU to free up space. I don't think it was addressing performance. @robeverest could tell you more.

Ah, where are you getting that "Internal representation of Storable array has changed" error from?

I have added #228 to the list. I am sure I have missed other important ones that need to be fixed so let us know or add them to the list yourself (although I'm not sure if you can edit the ticket).

**Comment by robeverest** [comment]
Trevors right. The memory management stuff wasn't intended to address any performance issues, though that is something worth looking at. It was mostly to handle out-of-memory processing and fix a number of concurrency bugs. 

@cpdurham I assume you're referring to #284? I'm looking at fixing that at the moment, so yes, that should be in a 1.0 release.

**Comment by cpdurham** [comment]
Oh, in that email thread, I realized that the performance issue was a memory leak, I'll email the package that illustrates the problem, I left comments to what each does, one of them is that internal representation error.

**Comment by mwu-tow** [comment]
Hi, great to see that big 1.0 release is coming. Thank you for your work!

I have a few questions:
1) Can we have Windows officially supported? I'd be happy to help with this. I haven't checked all the listed packages yet but AFAIK the needed changes would be:
* for `accelerate-cuda`: it waits for https://github.com/mainland/language-c-quote/pull/53, see https://github.com/AccelerateHS/accelerate/issues/234 for all the details. I have it working with my forks. Alternatively, other workaround would need to be devised, so the Mainland's `language-c-quote` doesn't have to be modified.
* for `cufft` — same solution as I did for `cuda` package, see: https://github.com/flowbox-public/cufft (I intend to submit PR some time later)

2) I'm very happy to hear that LLVM backend will receive its initial release. Has the work progressed beyond what's currently in the repository? How feature-complete will it be?

3) Has been the `invalid device context` issue been solved / is planned to be solved in the release (it was discussed in #261 and few other places)? Currently when I build the nbody sample from `accelerate-examples` and run it, it randomly either works or fails with said error. This looks like quite serious issue.

**Comment by tmcdonell** [comment]
@cpdurham Is there a ticket for that issue already we can put into the above list? Otherwise let's create a new one with your sample program to keep track of it.

@mwu-tow Windows support is on the list, although I will need your help in driving that one forward. We should look at this `invalid device context` bugs as well, they are quite serious. As for the LLVM backend I don't yet have a plan for how feature-complete it will be for this release. I have not worked on it in a while, but was going to start hacking on that again over the next few weeks.

**Comment by cpdurham** [comment]
I didn't create a ticket, I'll let you guys do that as you'll probably be able to be more descriptive of the actual issue or issues.

**Comment by tmcdonell** [comment]
@cpdurham submitted as #286

**Comment by tmcdonell** [comment]
https://mail.haskell.org/pipermail/haskell-cafe/2017-March/126651.html

**Comment by mchakravarty** [comment]
👍🏼🎉👏🏼🎊
