### ISSUE TITLE
Preparation for GHC 8.0

### ISSUE THREAD

**Issue by tmcdonell** [AccelerateHS/accelerate#303]
We should really make sure Accelerate and friends compile with GHC 8 before it is released. We have had problems before...

Currently (RC2) I am getting stuck with the following failures in dependencies:
- [x] accelerate
  - [x] sebastiaanvisser/fclabels#31
  - [x] gregorycollins/hashtables#29 (ghc regression, fixed)
- [x] accelerate-cuda
  - [x] memory (requires github version)
  - [x] bmillwood/haskell-src-meta#56
- [x] accelerate-llvm
  - [ ] llvm-general-pure
  - [x] atomic-primops rrnewton/haskell-lockfree#55
- [x] accelerate-llvm-native
- [x] accelerate-llvm-ptx
- [x] accelerate-io
  - [x] repa (requires github version)
- [x] accelerate-fft
- [x] accelerate-examples
- [x] linear-accelerate
- [x] lens-accelerate
- [x] https://github.com/tmcdonell/cuda/issues/39

**Comment by alexanderkjeldaas** [comment]
Accelerate is no longer in stackage (nightly) because of some GHC 8 issue (I presume).  I would be great to get it back.

**Comment by tmcdonell** [comment]
I'll see if I can do a quick patch release for the (now very old) 0.15 version on Hackage.

Do you know if I upload a new version on Hackage, will that automatically be picked up by stackage nightly?

**Comment by mchakravarty** [comment]
@tmcdonell I think, you need to edit https://github.com/fpco/stackage/blob/master/build-constraints.yaml to add accelerate again and submit a pull request. (Much like the instructions for new packages on the frontage of stockage.org.)

**Comment by tmcdonell** [comment]
Accelerate is [back in stackage](https://github.com/fpco/stackage/pull/1556).

**Comment by mchakravarty** [comment]
👍
