### ISSUE TITLE
TODO: feature/sequences branch

### ISSUE THREAD

**Issue by tmcdonell** [AccelerateHS/accelerate#382]
I'm just going to start adding notes/nits here as I look over the sequences code. Things to do / clean up / discuss / etc. before the merge into master.

 - [ ] There are so. many. warnings.
 - [ ] Stylistic changes; e.g.
     - spacing and alignments (consistency)
     - layout / organisation; e.g. helper functions defined far from their use site (for no reason)
 - [ ] The tuple fusion story
     - `eltFlavour`; yuck. 
     - The comment in AccelerateHS/accelerate@11622cb7758872c756f2ba33ed2770403c86609e is wrong, so I'm not sure what the motivating use case for disabling this was (I'm sure there was one, I want to know what it was). Check for other "temporarily disabled" things which should be addressed.
 - [x] `SeqIndex` offends me
 - [ ] graphviz support

**Comment by robeverest** [comment]
With regard to the comment about fusing through tuples and constant time unzip, here's a concrete example. It's somewhat artificial, but the general shape of it is not.

```
*Data.Array.Accelerate> let f x = let (as, bs) = unzip (map (\x -> lift (x,x+1)) x) in zipWith (*) as bs :: Acc (Vector Int)
```

Under `master`, this does not completely fuse (as is expected due to the use of tuples).

```
\a0 -> let a1 = map (\x0 -> (x0,1 + x0)) a0 in
       let a2 = map (\x0 -> #1 x0) a1 in
       let a3 = map (\x0 -> #0 x0) a1
       in generate (intersect (shape a2) (shape a3)) (\x0 -> (a2!x0) * (a3!x0))
```

With the tuple fusion available on `feature/sequences` and constant time unzipping turned OFF, it does fuse.

```
\a0 -> map (\x0 -> x0 * (1 + x0)) a0
```

However, if we turn constant time unzipping back ON, it's no longer fusing.

```
\a0 -> let a1 = map (\x0 -> (x0,1 + x0)) a0 in
       let a2 = map (\x0 -> #1 x0) a1 in
       let a3 = map (\x0 -> #0 x0) a1
       in generate (intersect (shape a2) (shape a3)) (\x0 -> (a2!x0) * (a3!x0))
```

These two features don't play nice together because constant time unzipping doesn't take into account how the result of the unzip is used. This was perfectly fine before, but with tuple fusion, it's something I'll need to look at. I'm not sure how to solve it, so any ideas are welcome.

**Comment by tmcdonell** [comment]
This could be a problem with `aletD`. The `unzipD` rule should only fire when given a manifest array, but clearly it is being given a delayed array, so what is forcing that initial `map` to be evaluated?

**Comment by tmcdonell** [comment]
(just to clarify this is a TODO list of stuff to look at later so that I don't forget... no need to investigate now)

**Comment by robeverest** [comment]
It could be, but I think it's more subtle than that. It's forcing the first `map` to be manifest because it's being "used" twice. That is technically true; its result is consumed by both halves of the unzip. It's just that both halves of that unzip should get embedded, but they're not.

To further complicate things I now realise I was wrong about tuple fusion being part of the problem here. This is all down to constant time unzipping. If I turn it off on `master` (just by commenting out that one line) we achieve fusion

```
\a0 -> map (\x0 -> x0 * (1 + x0)) a0
```

This issue should perhaps be split out into a different ticket, and at some point, after the Haskell Symposium deadline, I can look at fixing it in `master`. We don't want the fix to be held up with all the rest of the sequences stuff.

**Comment by tmcdonell** [comment]
Interesting. Okay, that should go in a separate issue then. We'll leave that for after HS though.

**Comment by tmcdonell** [comment]
```haskell
t7 :: Acc (Vector Float, Vector Float)
t7 =
  let xs = use (fromList (Z:.10) [0..]) :: Acc (Vector Float)
      ys = lift ( A.map (+1) xs
                , ( A.enumFromN (constant (Z:.20)) 0
                  , A.scanl (+) 0 xs
                  )
                )
  in
  lift ( A.zipWith (+) (A.afst ys) (A.afst (A.asnd ys))
       , A.zipWith (*) (A.afst ys) (A.asnd (A.asnd ys))
       )
```
