### ISSUE TITLE
Release 1.1

### ISSUE THREAD

**Issue by tmcdonell** [AccelerateHS/accelerate#394]
I'd like to make a new release soon (i.e. before leaving for icfp). This is my TODO list for that...

## TODO
- [x] cabal library builds using `runQ` from CPU backend.
- [x] updates for llvm-5 (I think all the necessary changes are already in llvm-hs).
- [x] **\<add your ticket of interest here\>**

## Broken
- This release will not include support on windows for runtime compilation (`run`, `runN`) in the accelerate-llvm-native backend (that platform needs an object file loader; see #395). `runQ` should work though.

## Uploads
- [x] accelerate
- [x] accelerate-llvm
- [x] accelerate-llvm-native
- [x] accelerate-llvm-ptx
- [x] accelerate-examples
- [x] accelerate-fft (bug fix release)
- [x] accelerate-blas (initial release)
- [x] cuda
- [x] cublas
- [x] cusparse
- [x] cusolver (?)
- [x] cufft
- [x] nvvm
- [x] colour-accelerate

## After
- [x] add to stackage (https://github.com/fpco/stackage/pull/2880)

**Comment by mchakravarty** [comment]
Sounds good 👍

**Comment by tmcdonell** [comment]
Although I doubt there will be further changes to `llvm-hs`, just waiting for LLVM-5.0 to be released (it is a few days behind schedule...)

**Comment by tmcdonell** [comment]
\\o/

**Comment by mchakravarty** [comment]
💯
